### ISSUE TITLE
Uncaught TypeError: container.lookupFactory is not a function

### ISSUE THREAD

**Issue by juanjobbio** [mtoygar/ember-cli-google-tag-manager#3]
At /addon/instance-initializers/gtm.js I'm getting this error
<img width="524" alt="screenshot 2018-10-24 at 10 05 16" src="https://user-images.githubusercontent.com/38909293/47419543-5bbb9b80-d774-11e8-870c-c8213ee26fab.png">
Apparently `var container = application.container;` is undefined

**Comment by jakenorthey** [comment]
This is patched in the fork below:
https://github.com/demirhanaydin/ember-cli-google-tag-manager

` yarn remove ember-cli-google-tag-manager`
`yarn add demirhanaydin/ember-cli-google-tag-manager`

**Comment by broerse** [comment]
@jacobnorthey can you make PR for this?

**Comment by jakenorthey** [comment]
https://github.com/Scalingo/ember-cli-google-tag-manager/pull/4

**Comment by broerse** [comment]
Thanks!
